name: Update Contributors

on:
  push:
    branches:
      - main

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          commit_message: "docs: update contributors"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
