name: Extension Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Build and compress
        run: |
          pnpm install
          pnpm build
          pnpm build:firefox
          cd build
          zip -r chrome-mv3-prod.zip chrome-mv3-prod
          cd firefox-mv2-prod
          zip -r ../firefox-mv2-prod.zip .

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./build/chrome-mv3-prod.zip
            ./build/firefox-mv2-prod.zip
